load("@io_bazel_rules_scala//scala:scala.bzl", "scala_library", "scala_binary", "scala_test")

scala_binary(
  name = "fx3d4",
  srcs = ["Fx3DShapeExample4.scala"],
  main_class = "Fx3DShapeExample4",
)
